language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

stages:
  - test
  - name: deploy
    if: branch = master



jobs:
  include:
    - script: echo "Linting tests (1)"
              npm run lint
    - script: echo "Running unit tests (2)"
              npm test
    - stage: Deploy
      script: skip
      deploy:
        provider: script
        script: echo "Deploying"
        on:
        branch: master