language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: eslint
      script: npm run lint

    - stage: unittest
      script: npm test

    - stage: deploy
      deploy:
        provider: script
        script: echo "Deploying"
        on:
          branch: master
