language: node_js
node_js:
  - "node"

cache:
  directories:
    - "node_modules"

stages:
  - test
  - name: deploy
    if: branch = master



jobs:
  include:
    - script: &.test1
    - script: &.test2
    - stage: Deploy
      script: skip
      deploy: &.deploy

.test1: |
  echo "Linting tests (1)"
  npm run lint

.test2: |
  echo "Running unit tests (2)"
  npm test

.deploy:
        provider: script
        script: echo "Deploying"
        on:
          branch: master

